mod setup_character_system;
mod setup_player_system;
mod setup_turn_order_system;
mod setup_camera_system;
mod setup_game_log_ui_system;
mod setup_ui_camera_system;
pub(crate) mod _plugin;
mod setup_map_system;
mod setup_player_inventory_ui_system;
mod setup_player_skills_ui_system;
